AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Guardfile
  Exclude:
    - vendor/**/*
    - cookbooks/**/*

ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
SignalException:
  Enabled: false
WordArray:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/*.rb
Layout/IndentHeredoc:
  Enabled: false
